Metrics/ClassLength:
  Max: 300

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*.rb"
    

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/MethodLength:
  Max: 15
  CountComments: false
  Exclude:
    - "db/migrate/*.rb"
    - "features/step_definitions/*.rb"

Metrics/LineLength:
  Max: 150

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

# https://github.com/presidentbeef/brakeman/issues/1664
# https://github.com/seattlerb/ruby_parser/issues/326
Style/HashSyntax:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "lib/tasks/**"
    - "spec/factories/*"
    - "spec/swagger_helper.rb"
    

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'spec/rails_helper.rb'
    - 'spec/response_helper.rb'
    - 'spec/controllers/concerns/respondable_spec.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'config/**/*'
    - 'ng/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'
    - 'app/views/api/v1/**/*'